version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform EKS Cluster

  Creates an EKS Cluster, Managed groups and Add Ons

  ## Examples

  ```hcl
  {{ include "./examples/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false