version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform GCP VPC

  Creates a full VPC network, including routes and Cloud-NAT

  ## Examples

  ```hcl
  {{ include "./examples/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false