version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform AWS Network

  Create full VPC Network including subnets, IGW, NATGW and Route-Tables

  ## Examples

  ```hcl
  {{ include "./examples/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false