version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform GCP VM

  Creates a GCP VM with a Firewall Group

  ## Examples

  ```hcl
  {{ include "./examples/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false